# finding if the customer has subscribed or not

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import statsmodels.formula.api as smf
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler as sps

In [2]:
bank = pd.read_csv ('C:/Users/harsh/Downloads/bank-full.csv',sep=';')
bank.head(300)

age           job   marital  education default  balance housing loan  \
0     58    management   married   tertiary      no     2143     yes   no   
1     44    technician    single  secondary      no       29     yes   no   
2     33  entrepreneur   married  secondary      no        2     yes  yes   
3     47   blue-collar   married    unknown      no     1506     yes   no   
4     33       unknown    single    unknown      no        1      no   no   
..   ...           ...       ...        ...     ...      ...     ...  ...   
295   56    technician  divorced    primary      no       13     yes   no   
296   31   blue-collar    single  secondary      no        3     yes   no   
297   24       student    single  secondary      no       82     yes   no   
298   42   blue-collar  divorced    primary      no       28     yes   no   
299   57    technician   married  secondary      no      792     yes   no   

     contact  day month  duration  campaign  pdays  previous poutcome   y  
0    unknown    5   may       261         1     -1         0  unknown  no  
1    unknown    5   may       151         1     -1         0  unknown  no  
2    unknown    5   may        76         1     -1         0  unknown  no  
3    unknown    5   may        92         1     -1         0  unknown  no  
4    unknown    5   may       198         1     -1         0  unknown  no  
..       ...  ...   ...       ...       ...    ...       ...      ...  ..  
295  unknown    5   may       357         2     -1         0  unknown  no  
296  unknown    5   may       200         2     -1         0  unknown  no  
297  unknown    5   may       204         2     -1         0  unknown  no  
298  unknown    5   may       126         3     -1         0  unknown  no  
299  unknown    5   may        65         2     -1         0  unknown  no  

[300 rows x 17 columns]

# Dropping all the unnecessary columns 

In [3]:
#bank.drop(['job','marital','education','housing','loan','contact','month'],axis= 1,inplace=True)
#bank.drop(['poutcome'],inplace=True,axis=1)
bank.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

# Seperating the x and y variables 

In [4]:
#X = pd.DataFrame(bank['age','default','balance','day','duration','campaign','pdays','previous'])
Y = pd.DataFrame(bank['y'])

X=bank[['age','balance','duration']]
X.head()
#Y=bank[['y']]
#Y.head()

age  balance  duration
0   58     2143       261
1   44       29       151
2   33        2        76
3   47     1506        92
4   33        1       198

In [5]:
Y.head()

y
0  no
1  no
2  no
3  no
4  no

# converting column of binomial string values into int values

In [6]:
Y.y[Y.y == 'yes'] = 1#,inplace=True
Y.y[Y.y == 'no'] = 0#,inplace = True
print(Y)

       y
0      0
1      0
2      0
3      0
4      0
...   ..
45206  1
45207  1
45208  1
45209  0
45210  0

[45211 rows x 1 columns]


In [7]:
Y.head()

y
0  0
1  0
2  0
3  0
4  0

In [8]:
X

age  balance  duration
0       58     2143       261
1       44       29       151
2       33        2        76
3       47     1506        92
4       33        1       198
...    ...      ...       ...
45206   51      825       977
45207   71     1729       456
45208   72     5715      1127
45209   57      668       508
45210   37     2971       361

[45211 rows x 3 columns]

In [9]:
X=X.astype('int')

In [10]:
Y=Y.astype('int')

In [11]:
np.ravel(X)

array([  58, 2143,  261, ...,   37, 2971,  361])

In [12]:
np.ravel(Y)

array([0, 0, 0, ..., 1, 0, 0])

In [13]:
pd.DataFrame(X)

age  balance  duration
0       58     2143       261
1       44       29       151
2       33        2        76
3       47     1506        92
4       33        1       198
...    ...      ...       ...
45206   51      825       977
45207   71     1729       456
45208   72     5715      1127
45209   57      668       508
45210   37     2971       361

[45211 rows x 3 columns]

In [14]:
pd.DataFrame(Y)

y
0      0
1      0
2      0
3      0
4      0
...   ..
45206  1
45207  1
45208  1
45209  0
45210  0

[45211 rows x 1 columns]

In [15]:
classifier = LogisticRegression()
model = classifier.fit(X,Y)

C:\Users\harsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [26]:
df = {'age':[58,51] ,'balance':[2143,825] ,'duration':[261,977]}


In [30]:
df= pd.DataFrame(df)
df

age  balance  duration
0   58     2143       261
1   51      825       977

In [29]:
model.predict(df)

array([0, 1])